### ISSUE TITLE
Zypper requires download of unsupported metadata type (sqlite)

### ISSUE THREAD

**Issue by dylanbartos** [openSUSE/libzypp#476]
In Downloader.cc, the "other" metadata type is excluded, as well as file types of "type_db" with the comment "(sqlite, ignored by zypp)". The file appears to be downloaded from a call to provideFile. 
https://github.com/openSUSE/libzypp/blob/1281bd8e228574b0c4c6b7618ff78cb3a1c24870/zypp/repo/yum/Downloader.cc#L121
https://github.com/openSUSE/libzypp/blob/1281bd8e228574b0c4c6b7618ff78cb3a1c24870/zypp/Fetcher.cc#L534

Additionally, it is noted in libsolv issue https://github.com/openSUSE/libsolv/issues/92 that sqlite metadata files are not supported.

This issue focuses around the Fetcher/MediaManager downloading the sqlite files uncessesarily and in some cases, requiring it even though it is an unsupported format. In the text snippet below, you can see the download process of an "-other.sqlite.bz2" file which gets downloaded. This comes from an online third party repository which hosts both the XML and sqlite metadata types. On one hand, the download is unnecessary and a waste of cycles/disk space.

```
2023-08-02 01:16:41 <1> hostname(15348) [zypp:fetcher] Fetcher.cc(locateInCache):347 start fetcher with 23 cache directories.
2023-08-02 01:16:41 <1> hostname(15348) [zypp:fetcher] Fetcher.cc(provideToDest):518 Not found in cache, retrieving...
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaSetAccess.cc(provide):221 Going to try to provide  file ./repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2 from media number 1
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaManager.cc(checkDesired):101 checkDesired(46): desired (cached)
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaManager.cc(checkDesired):101 checkDesired(46): desired (cached)
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaMultiCurl.cc(doGetFileCopy):1334 dest: /var/tmp/AP_0xhfB0lp/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaMultiCurl.cc(doGetFileCopy):1335 temp: /var/tmp/AP_0xhfB0lp/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2.new.zypp.bOsPUn
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaCurl.cc(doGetFileCopyFile):1501 ./repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaCurl.cc(doGetFileCopyFile):1511 URL: http://URL/repos/CAH-misc/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaMultiCurl.cc(progressCallback):1284 looks_like_metalink_fd: 0
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaMultiCurl.cc(doGetFileCopy):1373 HTTP response: 200
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaMultiCurl.cc(looks_like_metalink):1240 looks_like_metalink(/var/tmp/AP_0xhfB0lp/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2.new.zypp.bOsPUn): 0
2023-08-02 01:16:41 <1> hostname(15348) [zypp] PathInfo.cc(rename):710 rename /var/tmp/AP_0xhfB0lp/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2.new.zypp.bOsPUn -> /var/tmp/AP_0xhfB0lp/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaMultiCurl.cc(doGetFileCopy):1493 done: /var/tmp/AP_0xhfB0lp/repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2{- 0640 0/0 size 3992}
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaHandler.cc(provideFile):1015 provideFile(./repodata/c793bdec7dcedc91f2009a7dbeccb25a7ca85473130e65d4607099dc3e4ba8e1-other.sqlite.bz2)
2023-08-02 01:16:41 <1> hostname(15348) [zypp++] MediaManager.cc(checkDesired):101 checkDesired(46): desired (cached)
```

On the other hand, if you are using a mirror which stages only the files which zypper supports (ie choosing not to download the -other.sqlite.bz2 file), then zypper errors and is unable to use the repository because it is requiring a file type which is not supported.

```
2023-08-02 06:28:52 <1> hostname(26208) [zypp:fetcher] Fetcher.cc(locateInCache):347 start fetcher with 15 cache directories.
2023-08-02 06:28:52 <1> hostname(26208) [zypp:fetcher] Fetcher.cc(provideToDest):518 Not found in cache, retrieving...
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaSetAccess.cc(provide):221 Going to try to provide  file ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2 from media number 1
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaManager.cc(checkDesired):101 checkDesired(30): desired (cached)
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaManager.cc(checkDesired):101 checkDesired(30): desired (cached)
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 MediaHandler.cc(getFile):1245 THROW:    File './repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2' not found on medium 'file:/opt/Mirror/repos/repo-852'
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 MediaSetAccess.cc(provide):234 CAUGHT:   File './repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2' not found on medium 'file:/opt/Mirror/repos/repo-852'
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaManager.cc(checkDesired):101 checkDesired(30): desired (cached)
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(getDetectedDevices):1398 No devices for this medium
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaSetAccess.cc(provide):246 Media couldn't provide file ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2 , releasing.
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaManager.cc(release):475 release(id=30)
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(release):751 Request to release attached media dir</opt/Mirror/repos/repo-852>, use count=1
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(release):758 Releasing media dir</opt/Mirror/repos/repo-852>
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(removeAttachPoint):181 MediaHandler - checking if to remove attach point
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(removeAttachPoint):202 MediaHandler - attachpoint is not temporary
2023-08-02 06:28:52 <1> hostname(26208) [zypp] MediaHandler.cc(release):812 Released: file:/opt/Mirror/repos/repo-852 not attached; localRoot "/opt/Mirror/repos/repo-852"
2023-08-02 06:28:52 <1> hostname(26208) [zypp] MediaManager.cc(releaseAll):514 Releasing all attached media
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaManager.cc(releaseAll):532 Media id 30 not attached 
2023-08-02 06:28:52 <1> hostname(26208) [zypp] MediaManager.cc(releaseAll):542 Exit
2023-08-02 06:28:52 <1> hostname(26208) [zypper++] media.cc(requestMedia):208 medium problem, url: file:/opt/Mirror/repos/repo-852, error 1, label '', #1
2023-08-02 06:28:52 <1> hostname(26208) [zypper] prompt.cc(get_prompt_reply):264 running non-interactively, returning a
2023-08-02 06:28:52 <1> hostname(26208) [zypp] MediaSetAccess.cc(provide):301 ProvideFile exception caught, callback answer: 0
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaSetAccess.cc(provide):305 Aborting
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 MediaSetAccess.cc(provide):308 THROW:    ABORT request: Aborting requested by user
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 History:
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - File './repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2' not found on medium 'file:/opt/Mirror/repos/repo-852'
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 Fetcher.cc(provideToDest):556 RETHROW:  ABORT request: Aborting requested by user
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 History:
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - Can't provide ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 
2023-08-02 06:28:52 <1> hostname(26208) [Progress++] ProgressData.cc(report):88 {#92|}END
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaManager.cc(close):298 Close to access handler using id 30 requested
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(release):744 Request to release media - not attached; eject ''
2023-08-02 06:28:52 <1> hostname(26208) [zypp] MediaAccess.cc(close):248 Close: file(file:/opt/Mirror/repos/repo-852 not attached; localRoot "/opt/Mirror/repos/repo-852") (OK)
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(release):744 Request to release media - not attached; eject ''
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(removeAttachPoint):181 MediaHandler - checking if to remove attach point
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] MediaHandler.cc(removeAttachPoint):202 MediaHandler - attachpoint is not temporary
2023-08-02 06:28:52 <1> hostname(26208) [zypp] PathInfo.cc(recursive_rmdir):435 recursive_rmdir /var/cache/zypp/raw/mirror-852rmDbhP 
2023-08-02 06:28:52 <1> hostname(26208) [zypp++] TmpPath.cc(~Impl):78 TmpPath cleaned up /var/cache/zypp/raw/mirror-852rmDbhP{d 0700 0/0}
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 RepoManager.cc(refreshMetadata):1220 CAUGHT:   ABORT request: Aborting requested by user
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 History:
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - Can't provide ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 
2023-08-02 06:28:52 <3> hostname(26208) [zypp] RepoManager.cc(refreshMetadata):1221 Trying another url...
2023-08-02 06:28:52 <3> hostname(26208) [zypp] RepoManager.cc(refreshMetadata):1233 No more urls...
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 RepoManager.cc(refreshMetadata):1234 THROW:    [mirror-852|file:/opt/Mirror/repos/repo-852] Valid metadata not found at specified URL
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 History:
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - ABORT request: Aborting requested by user
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - Can't provide ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 repos.cc(build_cache):469 CAUGHT:   [mirror-852|file:/opt/Mirror/repos/repo-852] Valid metadata not found at specified URL
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 History:
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - ABORT request: Aborting requested by user
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166  - Can't provide ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2
2023-08-02 06:28:52 <5> hostname(26208) [zypp] Exception.cc(log):166 
2023-08-02 06:28:52 <3> hostname(26208) [zypper] repos.cc(build_cache):470 Error writing to cache db
2023-08-02 06:28:52 <2> hostname(26208) [zypper] repos.cc(do_init_repos):906 Skipping repository 'mirror-852' because of the above error.
```

**Comment by mlandres** [comment]
@dylanbartos we'd need to see the third party repositories `rpodata/repomd.xml`. This master index describes all data files the repository offers. The filtering in yum/Downloader.cc happens according to the `data type` the index advertises.
```
<repomd>
  ...
  <data type="other">
    ...
    <location href="repodata/other.xml.gz"/>
  </data>
  <data type="other_db">
    ....
    <location href="repodata/other.sqlite.bz2"/>
</data>
  ...
```
The data type for the sqlite databases has to have a "_db" suffix. If such files are downloaded by zypp, they are most probably not advertised correctly in the `repomd.xml`.

**Comment by dylanbartos** [comment]
@mlandres Here's the repomd. Thanks for taking a look. The `other_db` type has a location of `repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2` which is noted in the initial logs I posted under the line:
`MediaSetAccess.cc(provide):221 Going to try to provide  file ./repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2 from media number 1`


```
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
 <revision>1689112567</revision>
<data type="filelists">
  <checksum type="sha256">d0770dd4048a94ace147fc108f942caaf78db1b327514b4572cdce234cdf2b2d</checksum>
  <open-checksum type="sha256">f428dcd880b6862d1dbffd394749feac2a6e8f4c162029e75efa2690a408cc55</open-checksum>
  <location href="repodata/d0770dd4048a94ace147fc108f942caaf78db1b327514b4572cdce234cdf2b2d-filelists.xml.gz"/>
  <timestamp>1689112574</timestamp>
  <size>1239723</size>
  <open-size>25238506</open-size>
</data>
<data type="primary">
  <checksum type="sha256">628af663ad537aaab32efecf233da46895e39e61d402accab67a7d964a8e272c</checksum>
  <open-checksum type="sha256">a22389e26a93336d05f3ddd692c52819f1272dcb4c2734d76da5d5cceb4a0d51</open-checksum>
  <location href="repodata/628af663ad537aaab32efecf233da46895e39e61d402accab67a7d964a8e272c-primary.xml.gz"/>
  <timestamp>1689112574</timestamp>
  <size>13990</size>
  <open-size>129564</open-size>
</data>
<data type="primary_db">
  <checksum type="sha256">16da61d018ad5d60237818674158fac6d2897d96682776ddc6f2b7a95e4a3910</checksum>
  <open-checksum type="sha256">6e3bf333808f836ba3347176c5df780dfeb5ef751e74f783d762d4f619cd4701</open-checksum>
  <location href="repodata/16da61d018ad5d60237818674158fac6d2897d96682776ddc6f2b7a95e4a3910-primary.sqlite.bz2"/>
  <timestamp>1689112578</timestamp>
  <database_version>10</database_version>
  <size>28528</size>
  <open-size>169984</open-size>
</data>
<data type="other_db">
  <checksum type="sha256">79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5</checksum>
  <open-checksum type="sha256">9cfd9240e20f5631a2b1b26db4da66f24dae676b23a466007d31a6ff3a2a3430</open-checksum>
  <location href="repodata/79cd5554a45f4f1b689bba64ef10f559d777a0a6c06b3d4767f8160fc22ffdc5-other.sqlite.bz2"/>
  <timestamp>1689112574</timestamp>
  <database_version>10</database_version>
  <size>5122</size>
  <open-size>16384</open-size>
</data>
<data type="other">
  <checksum type="sha256">12fe1966870d995595ad88b0af8111a8fe8bf3af8b4459fe36ebd5dbc75b10f7</checksum>
  <open-checksum type="sha256">853e3ca3b8cb0c64dc762e5878d8713a1d83be09c1741425068219821787da7a</open-checksum>
  <location href="repodata/12fe1966870d995595ad88b0af8111a8fe8bf3af8b4459fe36ebd5dbc75b10f7-other.xml.gz"/>
  <timestamp>1689112574</timestamp>
  <size>3848</size>
  <open-size>14471</open-size>
</data>
<data type="filelists_db">
  <checksum type="sha256">2e49c303269f5f02493dbf1fff3b0f9ae43da74e97e07777447b37cbfa405e6f</checksum>
  <open-checksum type="sha256">c3115a6af10a6100399acaddc8ccaee211ad4940a3429058f8b93a7dc9da42ed</open-checksum>
  <location href="repodata/2e49c303269f5f02493dbf1fff3b0f9ae43da74e97e07777447b37cbfa405e6f-filelists.sqlite.bz2"/>
  <timestamp>1689112578</timestamp>
  <database_version>10</database_version>
  <size>1501498</size>
  <open-size>15654912</open-size>
</data>
</repomd>
```

**Comment by mlandres** [comment]
The repoindex looks good indeed. May it be you are using a quite old libzypp version?
( `grep libzypp: ` in the logfile will reveal the version)

AFAICS skipping the _db files was added 2020 in commit 4d4024626da2a157e5b36c06369b1d9cc40f602d for libzypp-17.22.0.

**Comment by mlandres** [comment]
So you are using Code12 (libzypp-16.x), not Code15 (libzypp-17.x). I'll have to check whether the fix is available in 12 at all.

**Comment by mlandres** [comment]
AFAICS the yum/Downloader in the SuSE-SLE-12-SP2-Branch branch does not filter out the _db files. It may need a small patch to work with Code12.

**Comment by mlandres** [comment]
Will be fixed in libzypp-16.22.9

**Comment by dylanbartos** [comment]
@mlandres Has 16.22.9 been released or is this issue remaining open until a release cycle becomes available?

**Comment by mlandres** [comment]
No, I just forgot to close the issue. There's no automated short-cuircuit between github issues  and SLE Maintenance, like we have for [bugzilla](https://bugzilla.suse.com). Bugzilla reports receive a trigger from maintenance as soon as the fix is released.

The fixed sources are available in [OBS](https://build.opensuse.org/package/show/zypp:SLE-12-SP2-Branch/libzypp). They can serve Leap-42.x and SLE-12-SPx (x=2 and higher, but Leap is out of maintenance AFAIK)

The sources have been submitted to SUSE maintenance but I don't know how long it will take to pass QA and become available in the official repos.
